import React, { useRef, useState } from 'react';
import { Recipe } from '../types';

interface SocialShareProps {
  recipe: Recipe;
  onClose: () => void;
  caption: string; // generated by AI
}

const SocialShare: React.FC<SocialShareProps> = ({ recipe, onClose, caption }) => {
  const [copied, setCopied] = useState(false);
  
  const copyCaption = () => {
    navigator.clipboard.writeText(caption);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
       <div className="bg-white rounded-3xl max-w-4xl w-full flex flex-col md:flex-row overflow-hidden shadow-2xl animate-fade-in-up">
          
          {/* Visual Preview (The "Image" to share) */}
          <div className="md:w-1/2 bg-gradient-to-br from-orange-100 to-rose-100 p-8 flex flex-col justify-between relative min-h-[400px]">
             <div className="absolute top-4 right-4 text-white/20 text-9xl pointer-events-none">
                <i className="fas fa-quote-right"></i>
             </div>
             
             <div>
               <div className="inline-block px-3 py-1 bg-black/10 text-black/60 rounded-full text-xs font-bold mb-4 uppercase tracking-wider">
                  CookingPro Recipe
               </div>
               <h2 className="text-4xl font-serif font-bold text-gray-900 leading-tight mb-4">
                  {recipe.title}
               </h2>
               <div className="flex gap-4 text-gray-700 font-medium">
                  <span><i className="far fa-clock"></i> {recipe.time}</span>
                  <span><i className="fas fa-fire"></i> {recipe.calories}</span>
               </div>
             </div>

             <div className="mt-8">
                <div className="flex items-center gap-3">
                   <div className="w-10 h-10 bg-white rounded-full flex items-center justify-center text-orange-600 shadow-sm">
                      <i className="fas fa-utensils"></i>
                   </div>
                   <div>
                      <p className="font-bold text-gray-900 text-sm">Made with CookingPro AI</p>
                      <p className="text-xs text-gray-500">Plan. Cook. Enjoy.</p>
                   </div>
                </div>
             </div>
          </div>

          {/* Controls */}
          <div className="md:w-1/2 p-8 flex flex-col">
             <div className="flex justify-between items-center mb-6">
                <h3 className="font-bold text-gray-800 text-lg">Share to Instagram</h3>
                <button onClick={onClose} className="text-gray-400 hover:text-gray-600">
                   <i className="fas fa-times text-xl"></i>
                </button>
             </div>

             <div className="flex-1 mb-6">
                <label className="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-2">AI Suggested Caption</label>
                <div className="bg-gray-50 p-4 rounded-xl border border-gray-200 text-gray-600 text-sm leading-relaxed h-48 overflow-y-auto whitespace-pre-wrap font-medium">
                   {caption}
                </div>
             </div>

             <div className="space-y-3">
                <button 
                  onClick={copyCaption}
                  className={`w-full py-3 rounded-xl font-bold flex items-center justify-center gap-2 transition-all ${copied ? 'bg-green-500 text-white' : 'bg-gray-100 text-gray-700 hover:bg-gray-200'}`}
                >
                   <i className={`fas ${copied ? 'fa-check' : 'fa-copy'}`}></i> {copied ? 'Caption Copied!' : 'Copy Caption'}
                </button>
                <button className="w-full py-3 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-xl font-bold hover:shadow-lg hover:opacity-90 transition-all flex items-center justify-center gap-2">
                   <i className="fab fa-instagram"></i> Open Instagram
                </button>
             </div>
             
             <p className="text-center text-xs text-gray-400 mt-4">
                Note: Web apps can't post directly to Instagram API. Copy the caption and screenshot/download the card!
             </p>
          </div>
       </div>
    </div>
  );
};

export default SocialShare;